### ISSUE TITLE
Unsupported package manager specification

### ISSUE THREAD

**Issue by panghaoyuan** [ycjcl868/monorepo#12]
## 问题：
执行`pnpm install`

出现错误
`Usage Error: Unsupported package manager specification (^pnpm@7.5.2,^pnpm,7.5.2)`

## 疑似问题原因
package.json中 
`packageManager: ^pnpm@7.0.0` 不支持
## 解决办法
```
{
  ... 
  "packageManager": "pnpm@7.0.0", 
  ...
}
```
修改后正常执行 `pnpm i`

**Comment by ycjcl868** [comment]
确实 https://nodejs.org/api/packages.html#packagemanager
