### ISSUE TITLE
请教一个问题，monorepo项目的分支管理应该怎么做呢~

### ISSUE THREAD

**Issue by YuYang019** [ycjcl868/monorepo#5]
如果把多个 app 应用也纳入 monorepo 进行管理，在项目高速迭代的时候，每个项目可能都有自己的 bug分支、特性分支、测试分支、部署分支等等。。。这块有没有什么好的解决方法呢

**Comment by ycjcl868** [comment]
个人感觉需要一套迭代研发模型，比如：
- 主干：master
- 迭代分支：release_*，每个 feat/bugfix/chore/tweak/... 需求以主干为准拉起新分支
- 开发分支：以迭代分支为基准，起的新分支进行开发

开发分支的代码变更，以 MR 形式合并至『迭代分支』，验证后合并主干并发布生产。

![image](https://user-images.githubusercontent.com/13595509/162657607-e90c206b-59f7-44a3-acec-c6a0dd853305.png)
