### ISSUE TITLE
请问如何结合dumi来生产组件的文档？如何同时渲染vue和react组件？

### ISSUE THREAD

**Issue by ghostrin** [ycjcl868/monorepo#8]
你的monorepo仓库思路很好，感谢你！我打算使用下。

在我使用过程中，我想在根据你的UI组件生成组件使用文档，包括组件预览，dumi是一个很好的方案，由于dumi是基于src向下查找md文件生成文档，就需要对你的ui目录结构进行修改，我修改过，有报错，还在调试；另一方面，当需要对组件进行预览时，dumi只支持react组件预览，不支持vue组件预览。请问以上两点有合适的解决方案吗？

非常期待，再次感谢！

**Comment by ycjcl868** [comment]
看起来 dumi 对 monorepo 的 `packages/` 文件变更监听有点问题，我先 `WATCH_IGNORED=none` 解决了（@peachscript）


![](https://user-images.githubusercontent.com/13595509/170510753-df4a6016-46b2-4252-9722-b765261c1a19.gif)

-------
