### ISSUE TITLE
请问引入packages必须要先打包吗。如果想直接引入里面的源码怎么办

### ISSUE THREAD

**Issue by sky124380729** [ycjcl868/monorepo#9]
我在使用cra创建的项目，引入内部包的时候，内部包文件是ts就会报错，是一定要先把内部包打包吗？
有直接引入内部包源码的demo吗

**Comment by ycjcl868** [comment]
在根目录执行 `pnpm i` 的时候，就会触发 package.json 的 `"prepare"` 脚本将内部包自动编译，所以不会报错的

**Comment by sky124380729** [comment]
可以直接引入不编译的源码吗，packages目录内容增大的话，如果每次变动都要将packages进行编译，效率不会降低吗

**Comment by ycjcl868** [comment]
不需要每次都编译，开发的时候直接 `pnpm run start --parallel --filter "dumi-app..."`，参考这个  https://github.com/ycjcl868/monorepo/pull/10
